companieshouse/xml-terraform

groups/xml-infrastructure/rds.tf

copy/paste error for referencing of the security group.

Referenced incorrect resource

---

groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars

var file change to test pipeline is picking up changes correctly.

formatting var file

---

groups/xml-infrastructure/profiles/heritage-development-eu-west-2/vars
groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/xml-infrastructure/profiles/heritage-staging-eu-west-2/vars
groups/xml-infrastructure/rds.tf
groups/xml-infrastructure/variables.tf

Adding minor_version option into code and setting false for staging and live

Adding minor_version option into code and setting false for staging and live

---

groups/xml-infrastructure/iam.tf
groups/xml-infrastructure/profiles/heritage-development-eu-west-2/vars
groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/xml-infrastructure/profiles/heritage-staging-eu-west-2/vars
groups/xml-infrastructure/templates/user_data.tpl

Updating instance count for frontends in all environments, adding correct logging permissions for cloudwatch logging and adding correct log file names for cloudwatch logging to userdata

Updating instance count for frontends in all environments

---

groups/xml-infrastructure/data.tf
groups/xml-infrastructure/templates/user_data.tpl

Updating user_data to use ansible-pull deployment method, will download deployment script and run it using inputs

Updating user_data to use ansible-pull deployment method

---

groups/xml-infrastructure/asg_backend.tf
groups/xml-infrastructure/asg_frontend.tf
groups/xml-infrastructure/iam.tf
groups/xml-infrastructure/locals.tf

Adding stop/start scheduling of ASGs for frontend and backend servers in non-production environment

Adding stop/start scheduling of ASGs for frontend and backend servers in non-production environment

---

groups/xml-infrastructure/alb-internal.tf
groups/xml-infrastructure/data.tf
groups/xml-infrastructure/locals.tf

Adding web subnets to XML Internal ALB security group for self-referencing purposes, XML calls XML

Adding web subnets to XML Internal ALB security group for self-referencing purposes, XML calls XML

---

groups/xml-infrastructure/README.md
groups/xml-infrastructure/data.tf
groups/xml-infrastructure/locals.tf
groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/xml-infrastructure/profiles/heritage-staging-eu-west-2/vars

increasing instance count on frontends for staging and live and adding user/pass input for cron entries

 Increasing instance count on frontends for staging and live and adding user/pass input for cron entries

---

groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/xml-infrastructure/profiles/heritage-staging-eu-west-2/vars

Add NFS on-premise (besides AWS mounts)

Add NFS on-premise (besides AWS mounts)

---

groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars

another fix: recent_filings

---

groups/xml-infrastructure/templates/bep_cron.tpl

change cron path for scripts in supportscripts

---

groups/xml-infrastructure/data.tf
groups/xml-infrastructure/templates/bep_user_data.tpl
groups/xml-infrastructure/templates/fe_user_data.tpl

Adding environment input to userdata and using this to form templateused by Nagios at userdata scripts

Adding environment input to userdata and using this to form nagios template

---

groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/xml-infrastructure/profiles/heritage-staging-eu-west-2/vars

Update RDS Maintenance Window

---

groups/xml-infrastructure/profiles/heritage-development-eu-west-2/vars
groups/xml-infrastructure/profiles/heritage-staging-eu-west-2/vars

Updated vars for Oracle DB minor version v24

Bumped oracle minor version to match deployed infrastructure

---

groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars

Updated live vars for upcoming minor version update

Bumped minor RDS version for Live

---

groups/xml-infrastructure/data.tf
groups/xml-infrastructure/templates/bep_user_data.tpl

Added vault data source to retrieve token and assign to template var
Updated template to write token to `.bash_profile`

Add FESS_TOKEN to XML BEP

---

groups/xml-infrastructure/templates/heritage-live-eu-west-2/bep_cron.tpl
groups/xml-infrastructure/templates/heritage-staging-eu-west-2/bep_cron.tpl

swap staging/live crons

---

groups/xml-infrastructure/templates/heritage-live-eu-west-2/bep_cron.tpl

align BE cron to what is the real cron on th EC2 atm

---

groups/xml-infrastructure/README.md
groups/xml-infrastructure/alb-external.tf
groups/xml-infrastructure/alb-internal.tf
groups/xml-infrastructure/asg_backend.tf
groups/xml-infrastructure/asg_frontend.tf
groups/xml-infrastructure/locals.tf
groups/xml-infrastructure/profiles/heritage-development-eu-west-2/vars
groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/xml-infrastructure/profiles/heritage-staging-eu-west-2/vars
groups/xml-infrastructure/sns.tf
groups/xml-infrastructure/variables.tf

Adding new ASG alarms for bep and fe, updating both ALBs alarms to latest module and adding SNS topic for XML alarms

Adding new ASG alarms for bep and fe, updating both ALBs alarms to latest module and adding SNS topic for XML alarms

---

groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/xml-infrastructure/profiles/heritage-staging-eu-west-2/vars

Bumped RDS engine versions to match deployed infrastructure

Bump RDS Engine Versions

---

groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars

Updated Live vars to remove references to onsite NFS mounts
NOTE: Not to be merged until change window

Remove onsite NFS Mounts

---

groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars

Added SG patterns to permit CHIPSDB access to XMLLIVE

Permit CHIPSDB Access to XML Live

---

groups/xml-infrastructure/profiles/heritage-development-eu-west-2/vars

Updated parameters and options to upgrade Dev RDS to Oracle 19
Resolves: CM-1417

Upgrade Dev RDS to Oracle 19

---

groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars
groups/xml-infrastructure/rds.tf

Updated parameters to upgrade Live RDS to Oracle 19

Upgrade Live RDS to Oracle 19

---

groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars

Enable RDS alarms in Live

---

groups/xml-infrastructure/README.md
groups/xml-infrastructure/iam.tf
groups/xml-infrastructure/rds.tf

Add support for EF presenter data buckets

---

groups/xml-infrastructure/data.tf
groups/xml-infrastructure/locals.tf
groups/xml-infrastructure/profiles/heritage-staging-eu-west-2/vars
groups/xml-infrastructure/variables.tf

Added data lookup to retrieve Test Concourse CIDRs from Vault
Added conditional local to extract CIDRs
Concatenated new local to existing `rds_ingress_cidrs`
Added boolean var to control conditional access
Updated Staging vars to enable Test access
Resolves: INC0296370

Conditionally allow RDS access from test concourse

---

groups/xml-infrastructure/profiles/heritage-live-eu-west-2/vars

Updated live parameters to
* Remove JVM option
* Disable auto minor version upgrades

Remove JVM option, disable auto version upgrades
